### ISSUE TITLE
Error 404 for "readme for installer"

### ISSUE THREAD

**Issue by roberwinkler** [JetStream96/QSimPlanner#10]
Hi,

the link in the text of your <code> page: https://github.com/JetStream96/QSimPlanner/blob/develop/src/Installer/readme.md
gives a 404

regards
Richard

**Comment by JetStream96** [comment]
It should be https://github.com/JetStream96/QSimPlanner/blob/develop/src/Installer/readme.txt

I will update the link later.

**Comment by JetStream96** [comment]
Fixed it.
