### ISSUE TITLE
NATS Download - Eastbound & Westbound XML

### ISSUE THREAD

**Issue by cjessen** [JetStream96/QSimPlanner#11]
It looks like the URL for the XML for the Eastbound and Westbound tracks are no longer available. 

http://qsimplan.somee.com/nats/Westbound.xml
http://qsimplan.somee.com/nats/Eastbound.xml

Is it possible to get these files included with the source code?

**Comment by JetStream96** [comment]
You can get the same xml files at the following address:
https://qsimplanner.azurewebsites.net/nats/Westbound.xml
https://qsimplanner.azurewebsites.net/nats/Eastbound.xml

Indeed the old links no longer work.

**Comment by cjessen** [comment]
Thanks!
