### ISSUE TITLE
Takeoff Performance B738

### ISSUE THREAD

**Issue by brittz** [JetStream96/QSimPlanner#12]
Is it possible to add other takeoff options for B738 like TO1 or TO2 and other flaps configurations? In SBRJ 
 for example is impossible to always takeoff with flap 5 and this make me to use another programs. How can I help you to make this improvement? I really like this project.

**Comment by JetStream96** [comment]
Yes it is possible but that involves manually converting charts to tables. If you want to do it, find the B738 FPPM online, go to chapter: 'Takeoff and landing', section 'Takeoff field limit - dry runway flaps 1'. Those are charts for each flaps and dry/wet runway.

To make it work in QSimPlanner, you will need to convert those charts into tables found in FCOM, chapter 'Performance dispatch', section '737-800/Takeoff/Takeoff field and climb limit weights'. There should be a corresponding table for each altitude and dry/wet condition.

It's quite a time-consuming task. If you have any question please feel free to ask. Sorry for the late reply.
