### ISSUE TITLE
mozglue.dll not found

### ISSUE THREAD

**Issue by CJPilot** [JetStream96/QSimPlanner#13]
Hello. I found this and was hopeing to use it for take-off calculations in the B738. However, when I try to run it, I get a mozglue.dll not found error. I installed Visual Studio 2012, but it still will not run.

As a side note, it would be very helpful if this was rewritten in C++ or Java.

**Comment by JetStream96** [comment]
Which version are you using? Can you send me the full error message or screenshot?

**Comment by CJPilot** [comment]
![screenshot 1](https://user-images.githubusercontent.com/36345936/43788636-f0b9cff2-9a3b-11e8-9c01-b657c729d1cb.png)
Using version 0.4.6

**Comment by JetStream96** [comment]
Is it possible that your anti-virus software deleted that file? You can try disabling the anti-virus and re-install QSimPlanner.

**Comment by CJPilot** [comment]
Umm... Is it possible to do that without disabling anti-virus? I'm on win10.

**Comment by JetStream96** [comment]
Maybe add mozglue.dll as exception in your anti-virus? The program needs that file to work.
