### ISSUE TITLE
Export error with X-Plane 11

### ISSUE THREAD

**Issue by kbcy** [JetStream96/QSimPlanner#14]
When exporting the route to x-plane 11 "fms plans" folder it fails to export. But there are no failure when exporting the flight plan to other options for x-plane 11 such as jar design and flight factor aircraft.

**Comment by JetStream96** [comment]
Thanks. Let me see if I can reproduce this error.

**Comment by rklomp** [comment]
This is caused by Navaids not being passed to the exporter (it is null).
https://github.com/JetStream96/QSimPlanner/blob/develop/src/QSP/RouteFinding/FileExport/Providers/XplaneProvider.cs#L26

Still trying to figure out where this should come from and how to pass it to the exporter.

**Comment by rklomp** [comment]
@kbcy , Can you test if this build works for you?
https://github.com/rklomp/QSimPlanner/releases/tag/v0.4.7-exportfix

**Comment by kbcy** [comment]
Tried that build and export to x-plane works. Thanks.
