### ISSUE TITLE
Unable to load navdata

### ISSUE THREAD

**Issue by merspieler** [JetStream96/QSimPlanner#6]
I've tryed to use the 0609 AIRAC circle cause i use it for vasfmc and it was the only one i could obtain for free.

When i try to set the "Nav Data Location" path it says "Database Status: Failed to load".

How can i debug this problem?

**Comment by JetStream96** [comment]
No that will not work. You need an AIRAC cycle for the Aerosoft Airbus A318/319/320/321.

**Comment by merspieler** [comment]
Then I can't use it :-(
