### ISSUE TITLE
New feature request: Auto Select Runway

### ISSUE THREAD

**Issue by winkerbie** [JetStream96/QSimPlanner#7]
I wonder if this is possible? when I press calculate route if the program auto-selects runway based on weather data

Thanks

**Comment by JetStream96** [comment]
Yes I can add that. There is one thing I am thinking about though. Which runway should be selected if the airport has four or more runways?

**Comment by winkerbie** [comment]
I guess they are parallel runways then make the selection random. Otherwise it should be the runway with the greatest head wind.

Also do you calculate the fuel with a fixed cost index? Or do you not take that into account at all

Thanks for your hard work

**Comment by JetStream96** [comment]
> I guess they are parallel runways then make the selection random. Otherwise it should be the runway with the greatest head wind.

Sound good. Probably also need to estimate the takeoff distance to filter out runways that are too short. I will add it soon.

> Also do you calculate the fuel with a fixed cost index? Or do you not take that into account at all

All data is from long range cruise (i.e. cruising at speed that gives 99% of max range).

**Comment by merspieler** [comment]
If you have aswell an airport moving map, you could use the rwy with with the least taxi distance to the parking position/gate.

**Comment by JetStream96** [comment]
I don't think that will be added any time soon. IMO the gate information is only useful if the aircraft position in the sim can be automatically detected. I am not very interested in implementing that. Of course, if you can contribute it would be totally welcomed.

**Comment by merspieler** [comment]
I'ld like to contribute it (iirc FSX has this information somewhere) but since I can't use the tool ( see #6 )
and i move on to flight gear on linux, I'm not that interrested anymore.

**Comment by JetStream96** [comment]
Thank you. The linked project is quite interesting. Btw, it's very likely that an AIRAC cycle will be bundled with our installer in the next version (maybe in 1 or 2 weeks).

**Comment by allebb** [comment]
Hey guys,

Just in response to the parking slot data, I believe you can get these by running the MakeRwys.exe program that you can download for free here: http://www.schiratti.com/dowson.html

It extracts all kinds of information from the Simulator such as Taxiways, Frequencies and Runways.

I've used it for extracting airport information for one of my projects (https://fsHhb.io) in the past too...

Let me know if you'd like me to help get the data for you, I'd be happy to assist/get involved with this project as I think it's great!

Cheers,
Bobby

**Comment by JetStream96** [comment]
Thanks allebb. I am a bit busy this week but I will look at the links you mentioned.

**Comment by allebb** [comment]
No problem David, I'm glad I could have helped though, should enable you to implement the feature request at least :)

Keep up the good work 👍 

Cheers,
Bobby

**Comment by JetStream96** [comment]
Just to add a note. This feature is implemented in the latest version (0.4.1). It does what winkerbie [proposed originally](https://github.com/JetStream96/QSimPlanner/issues/7#issuecomment-337010896). The runway is selected automatically when the ICAO code is entered in the fuel planning page.

As for the gate position and simulator integration, it doesn't seem worth it to do all the work just to select an runway. Nevertheless, it's a cool idea. I think it can be implemented along with other features like moving map and trajectory tracking. Feel free to open another issue for further discussion.
