### ISSUE TITLE
Featur request: Build instructions

### ISSUE THREAD

**Issue by merspieler** [JetStream96/QSimPlanner#8]
Add instructions on how to build the program (if possible add a Makefile and make it independent from a windows platform).

**Comment by JetStream96** [comment]
I added the instructions. Now there is a link in 'Building' section in readme.

I currently have no plan for cross-platform compatibility. Unfortunately, the UI of this project is based on WinForm, which can only be used on Windows. Also, this entire application needs to be ported from .NET framework to .NET core if we want it to be cross-platform. This is a huge amount of work I think.

**Comment by merspieler** [comment]
rewrite it in a propper, independent language, eg. C++ :P

**Comment by JetStream96** [comment]
Not me. Not me >.<
