### ISSUE TITLE
Feature request: Take off performance for the TFDi 717

### ISSUE THREAD

**Issue by julianpoma** [JetStream96/QSimPlanner#9]
Let me first congratulate you for the amazing app you have developed. I am astonished! Keep up the good work.

As the title says,  im requesting this feature! I have an FCOM that may be helpful. If you are interested, just contact me and I will happily send it to you :)

Thank you again for this gem!

**Comment by JetStream96** [comment]
Thank you. It would be very helpful. I already sent an email to you. :)

**Comment by julianpoma** [comment]
Email sent ! :)
